spring.application.name=meal-vote-bot

spring.datasource.url=jdbc:h2:mem:mealvotebot;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
#spring.jackson.serialization.WRITE_DATES_AS_TIMESTAMPS=false

bot.token=${BOT_TOKEN:8701338978:AAFnVoK3NCbXkdRXFbWsDHF_1QgNMx1Fyug}
bot.username=${BOT_USERNAME:DailyMealVoteBot}
bot.reminder-cron=0 0 9 * * *
bot.change-deadline=11:00
bot.admin-ids=${BOT_ADMIN_IDS:}
bot.default-language=uz

logging.level.org.springframework=INFO
logging.level.com.example.demo=DEBUG
