spring.application.name=oshxona-meal-bot

spring.profiles.active=dev

# ====================== TELEGRAM BOT CONFIG ======================
bot.token=8069557421:AAE--5DTIowhnUr9WJGVux8pDEJPHE1_3xk
bot.username=visolatestbot

# Qo'shimcha sozlamalar
bot.reminder-cron=0 0 9 * * *
bot.change-deadline=11:00
bot.admin-ids=1988818507,638206964
bot.default-language=uz

# H2 console (test uchun)
spring.h2.console.enabled=true

# Actuator
management.endpoints.web.exposure.include=health,info

# ====================== API CONFIG ======================
# Server port
server.port=8080

# Jackson JSON configuration
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.time-zone=UTC
spring.jackson.default-property-inclusion=non_null