# =============================================
# application.properties — umumiy sozlamalar
# Profil-specific fayllar ustiga yoziladi:
#   application-dev.properties  (development)
#   application-prod.properties (production)
# =============================================
# =============================================
# application.properties
# =============================================

spring.application.name=oshxona-meal-bot

spring.profiles.active=${BOT_PROFILE:dev}

# ====================== TELEGRAM BOT ======================
# Eng muhim: botConfig classida qanday nom ishlatilgan bo'lsa, shu nomni ishlatish kerak
bot.token=${BOT_TOKEN:8701338978:AAFnVoK3NCbXkdRXFbWsDHF_1QgNMx1Fyug}
bot.username=${BOT_USERNAME:@pdp_meal_system_bot}

# Qo'shimcha bot sozlamalari
bot.reminder-cron=${BOT_REMINDER_CRON:0 0 9 * * *}
bot.change-deadline=${BOT_CHANGE_DEADLINE:11:00}
bot.admin-ids=${BOT_ADMIN_IDS:1988818507,638206964}
bot.default-language=${BOT_DEFAULT_LANGUAGE:uz}

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when-authorized
